scraping:
    driver_path: chromedriver.exe
    base_url: https://finance.yahoo.com/quote/AAPL/history?p=AAPL
    page_title_text: People Also Watch
    page_title_selector: #recommendations-by-symbol > h2:nth-child(1) > span:nth-child(1)
    selector_price: tr.Fz\(s\) > td:nth-child(2) > span:nth-child(1)
logging:
    log_file_name: main.log