scraping:
  driver_path: 'chromedriver.exe'
  base_url: 'https://www.thebalance.com/national-debt-by-year-compared-to-gdp-and-major-events-3306287'
  page_title_text: 'U.S. National Debt by Year'
  page_title_selector: '#article-heading__container_2-0'
  selector_price: '.mntl-sc-block-table__table > tbody:nth-child(6) > tr > td:nth-child(3)'
logging:
  log_file_name: 'main.log'